try {
  // ...
} catch (err) {
  console.log(err.message);
}